/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#006E2A',
        'primary-dark': '#00531E',
        'primary-light': '#00C853',
        secondary: '#00E676',
        accent: '#FFD54F',
        background: '#F3FCE8',
        'background-dark': '#E7F1E3',
        card: '#FFFFFF',
        text: '#151E15',
        subtext: '#3C4A3C',
        border: '#E5E7EB',
        'outline-variant': '#BBCCBA',
        'surface-container': '#E7F1E3',
        'surface-container-high': '#DCE8D3',
        'surface-container-low': '#EDF6E8',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-md': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'display-sm': ['40px', { lineHeight: '1.2' }],
        'display-xs': ['32px', { lineHeight: '1.2' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'headline-md': ['32px', { lineHeight: '1.3' }],
        'headline-sm': ['28px', { lineHeight: '1.35' }],
        'title-lg': ['24px', { lineHeight: '1.4' }],
        'title-md': ['20px', { lineHeight: '1.4' }],
        'title-sm': ['16px', { lineHeight: '1.5' }],
        'body-lg': ['18px', { lineHeight: '1.6' }],
        'body-md': ['16px', { lineHeight: '1.6' }],
        'body-sm': ['14px', { lineHeight: '1.5' }],
        'label-lg': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        'label-md': ['12px', { lineHeight: '1.3', letterSpacing: '0.05em' }],
        'label-sm': ['11px', { lineHeight: '1.3', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        '2xs': '4px',
        xs: '8px',
        sm: '12px',
        DEFAULT: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '40px',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 20px 60px -15px rgba(0, 0, 0, 0.06)',
        'soft-lg': '0 25px 70px -20px rgba(0, 0, 0, 0.1)',
        glow: '0 0 0 4px rgba(0, 200, 83, 0.12)',
        'glow-lg': '0 0 0 8px rgba(0, 200, 83, 0.16)',
        inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
        '3d': '0 4px 14px 0 rgba(0, 0, 0, 0.08)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-primary': 'linear-gradient(135deg, #006E2A, #00C853)',
        'gradient-hero': 'radial-gradient(ellipse at 30% 0%, rgba(0, 200, 83, 0.15) 0%, transparent 50%), radial-gradient(ellipse at 70% 100%, rgba(0, 230, 118, 0.1) 0%, transparent 50%)',
        'gradient-card': 'linear-gradient(145deg, rgba(255,255,255,0.9), rgba(255,255,255,0.6))',
      },
      spacing: {
        'section-padding': '120px',
        'section-padding-mobile': '64px',
        'section-padding-lg': '140px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'gutter': '24px',
        'container-max': '1440px',
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '20px',
          md: '32px',
          lg: '80px',
        },
        screens: {
          sm: '640px',
          md: '768px',
          lg: '1024px',
          xl: '1280px',
          '2xl': '1440px',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'fade-in-down': 'fadeInDown 0.6s ease-out forwards',
        'slide-in-left': 'slideInLeft 0.6s ease-out forwards',
        'slide-in-right': 'slideInRight 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.5s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'counter': 'counter 2s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(0, 200, 83, 0.2)' },
          '50%': { boxShadow: '0 0 40px rgba(0, 200, 83, 0.4)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
