'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'vi' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Header
    menu: 'Menu',
    search: 'Tìm kiếm',
    registerConsultation: 'Tư vấn đăng kí',
    supportCenter: 'Trung tâm Hỗ trợ',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    closeMenu: 'Đóng menu',
    openMenu: 'Mở menu',
    downloadApp: 'Tải ứng dụng',
    joinBiteo: 'Tham gia Biteo',
    shopperStaff: 'Nhân viên đi chợ hộ',
    shoppingAssistant: 'Hỗ trợ mua sắm',
    biteoAffiliate: 'CTV của Biteo',
    collaborator: 'Cộng tác viên',
    registerStore: 'Đăng ký Cửa hàng',
    businessPartner: 'Hợp tác kinh doanh',
    creatorMarketing: 'Creator/Tiếp thị',
    contentMarketing: 'Content & Marketing',
    becomePartner: 'Trở thành Đối tác',

    // Hero
    heroBadge: 'Khám phá nhịp sống sôi động cùng Biteo',
    heroTitle: 'Gắn kết cộng đồng',
    heroSubtitle: 'chia sẻ niềm vui.',
    heroDescription: 'Từ đi chợ hộ, đặt món đến chia sẻ những địa điểm thú vị cùng bạn bè. Tất cả trong một trải nghiệm mượt mà.',
    downloadNow: 'Tải ứng dụng ngay',
    watchIntro: 'Xem giới thiệu',
    users: 'Người dùng',
    rating: 'Đánh giá',
    support: 'Hỗ trợ',

    // Feature Cards
    orderFood: 'Đặt món',
    groceryShopping: 'Đi chợ hộ',
    travel: 'Du lịch',
    explore: 'Khám phá',

    // Trust Bar
    ecosystemTitle: 'Một hệ sinh thái – Nhiều nhu cầu',
    ecosystemSubtitle: 'Tất cả trong một ứng dụng duy nhất',
    video: 'Video',
    culinary: 'Ẩm thực',
    shopping: 'Mua sắm',
    localExplore: 'Khám phá',

    // Stats Section
    techServingLife: 'Công nghệ phục vụ cuộc sống.',
    statsDescription: 'Mọi tính năng của Biteo đều được thiết kế hướng đến sự đơn giản, tiện lợi và dễ sử dụng. Chúng tôi luôn cải tiến trải nghiệm để người dùng, doanh nghiệp và đối tác có thể kết nối nhanh chóng, sử dụng hiệu quả và cùng nhau tạo nên một hệ sinh thái công nghệ dành cho người Việt.',
    multiService: 'Đa dịch vụ',
    localConnect: 'Kết nối địa phương',
    seamlessExperience: 'Trải nghiệm liền mạch',
    opportunity: 'Cơ hội cho mọi người',

    // Service Ecosystem
    oneApp: 'Một ứng dụng.',
    millionExperiences: 'Hàng triệu trải nghiệm.',
    ecosystemDescription: 'Chỉ với một ứng dụng, người dùng có thể khám phá video ngắn, tìm kiếm địa điểm ăn uống, đặt bàn, đặt phòng lưu trú, mua sắm đặc sản địa phương, sử dụng dịch vụ đi chợ hộ và nhiều tiện ích khác.',
    discover: 'Khám phá',
    entertainmentVideo: 'Video giải trí',
    entertainmentDesc: 'Khám phá video ngắn, nội dung địa phương và những trải nghiệm thú vị mỗi ngày.',
    culinaryDesc: 'Tìm kiếm nhà hàng, quán ăn, quán cà phê và những hương vị đặc sắc quanh bạn.',
    travelDesc: 'Khám phá điểm đến, đặt phòng và lên kế hoạch cho những hành trình đáng nhớ.',
    shoppingDesc: 'Khám phá đặc sản địa phương và những sản phẩm được tuyển chọn.',
    groceryDesc: 'Mua thực phẩm và nhu yếu phẩm nhanh chóng, tiện lợi ngại tại nơi bạn sống.',
    localDiscoverTitle: 'Khám phá địa phương',
    localDiscoverDesc: 'Tìm kiếm những địa điểm, dịch vụ và trải nghiệm đặc sắc quanh bạn.',

    // Opportunities
    opportunitiesTitle: 'Cùng Biteo tạo nên',
    newOpportunities: 'những cơ hội mới',
    opportunitiesDesc: 'Không chỉ là một ứng dụng, Biteo còn tạo ra cơ hội cho cộng tác viên và đối tác trên toàn quốc tham gia xây dựng hệ sinh thái số.',
    collaborators: 'Cộng tác viên',
    collabDesc: 'Tham gia hệ sinh thái và tạo thêm nguồn thu nhập.',
    becomeCollaborator: 'Trở thành cộng tác viên',
    businessPartnerTitle: 'Đối tác kinh doanh',
    businessPartnerDesc: 'Đưa sản phẩm và dịch vụ đến hàng triệu khách hàng.',
    registerPartner: 'Đăng ký đối tác',
    localPartner: 'Đối tác địa phương',
    localPartnerDesc: 'Cùng Biteo thúc đẩy kinh tế và chuyển đổi số tại địa phương.',
    learnMore: 'Tìm hiểu thêm',

    // Business Section
    forBusiness: 'DÀNH CHO DOANH NGHIỆP',
    bringBusinessCloser: 'Đưa doanh nghiệp địa phương đến gần khách hàng hơn',
    businessDesc: 'Biteo đồng hành cùng nhà hàng, quán cà phê, khách sạn, homestay, cửa hàng đặc sản, siêu thị mini và nhiều mô hình kinh doanh khác trong quá trình chuyển đổi số.',
    reachNewCustomers: 'Tiếp cận khách hàng mới',
    increaseRevenue: 'Tăng doanh thu',
    manageEffectively: 'Quản lý hoạt động hiệu quả',
    buildDigitalBrand: 'Xây dựng thương hiệu số',
    sustainableGrowth: 'Phát triển bền vững',
    becomeBiteoPartner: 'Trở thành đối tác Biteo',
    businesses: 'Doanh nghiệp',
    provinces: 'Tỉnh thành',
    appUsers: 'Người dùng',

    // Support Section
    support: 'Hỗ trợ',
    supportTitle: 'Trung tâm',
    supportTitleHighlight: 'Hỗ trợ',
    supportDesc: 'Đội ngũ Biteo luôn sẵn sàng hỗ trợ bạn 24/7. Liên hệ ngay nếu cần giúp đỡ.',
    liveChat: 'Chat trực tuyến',
    liveChatDesc: 'Trò chuyện với đội ngũ hỗ trợ 24/7',
    email: 'Email',
    emailDesc: 'Gửi yêu cầu hỗ trợ qua email',
    responseIn24h: 'Phản hồi trong 24h',
    hotline: 'Hotline',
    hotlineDesc: 'Gọi trực tiếp để được tư vấn',
    faqCenter: 'Trung tâm FAQ',
    faqCenterDesc: 'Tìm câu trả lời nhanh chóng',
    alwaysUpdated: 'Luôn cập nhật',
    faqTitle: 'Câu hỏi thường gặp',
    faqSubtitle: 'Tìm nhanh câu trả lời cho những vấn đề phổ biến',
    contactSupport: 'Liên hệ hỗ trợ',
    faqQ1: 'Làm sao để đăng ký làm CTV của Biteo?',
    faqA1: 'Bạn có thể đăng ký trực tiếp tại trang đăng ký CTV hoặc liên hệ hotline 0986498899.',
    faqQ2: 'Biteo có hỗ trợ giao hàng trên toàn quốc không?',
    faqA2: 'Hiện tại Biteo đang mở rộng dịch vụ tại các tỉnh thành lớn.',
    faqQ3: 'Tôi gặp sự cố khi sử dụng ứng dụng?',
    faqA3: 'Liên hệ hotline 0986498899 hoặc gửi email về support@biteo.vn.',

    // Download App
    platformExperiences: 'Một nền tảng, mọi trải nghiệm.',
    downloadDesc: 'Khám phá, kết nối và tận hưởng mọi tiện ích trong một ứng dụng duy nhất. Tải ngay để bắt đầu trải nghiệm.',
    downloadOn: 'Tải trên',
    availableOn: 'Có sẵn trên',
    scanQR: 'Quét mã QR',
    scanQRDesc: 'để tải ứng dụng',
    iosAndroid: 'iOS & Android',
    topRestaurants: 'Top quán ngon',
    nearYou: 'Gần bạn',

    // Final CTA
    readyExperience: 'Sẵn sàng trải nghiệm Biteo?',
    ctaDesc: 'Tham gia hệ sinh thái Biteo và khám phá một cách hoàn toàn mới để kết nối với cuộc sống.',
    exploreBiteo: 'Khám phá Biteo',

    // Footer
    aboutBiteo: 'Về Biteo',
    contact: 'Liên hệ',
    services: 'Dịch vụ',
    registerBusiness: 'Đăng ký doanh nghiệp',
    supportCenter: 'Trung tâm hỗ trợ',
    termsOfUse: 'Điều khoản sử dụng',
    privacyPolicy: 'Chính sách bảo mật',
    partnerPolicy: 'Chính sách đối tác',
    footerDesc: 'Biteo – Nền tảng công nghệ đa dịch vụ kết nối người dùng, doanh nghiệp và đối tác trong một hệ sinh thái số toàn diện.',
    biteo: 'Biteo',
    legal: 'Pháp lý',
    partners: 'Đối tác',

    // Registration Pages
    register: 'Đăng ký',
    fullName: 'Họ và tên',
    phone: 'Số điện thoại',
    emailAddress: 'Địa chỉ email',
    address: 'Địa chỉ',
    city: 'Tỉnh/Thành phố',
    district: 'Quận/Huyện',
    ward: 'Phường/Xã',
    submit: 'Gửi đăng ký',
    cancel: 'Hủy',
    required: 'Bắt buộc',
    optional: 'Tùy chọn',
    success: 'Đăng ký thành công!',
    error: 'Có lỗi xảy ra. Vui lòng thử lại.',
    agreeTerms: 'Tôi đồng ý với Điều khoản sử dụng và Chính sách bảo mật',

    // Common
    home: 'Trang chủ',
    back: 'Quay lại',
    next: 'Tiếp theo',
    previous: 'Trước',
    close: 'Đóng',
    save: 'Lưu',
    loading: 'Đang tải...',
    message: 'Nội dung',
    subject: 'Chủ đề',
    feedback: 'Góp ý sản phẩm',
    report: 'Báo cáo sự cố',
    other: 'Khác',
    businessHours: 'Giờ làm việc',
    office: 'Văn phòng',
    weekdays: 'Thứ 2 - Thứ 6',

    // Terms Page
    termsTitle: 'Điều khoản Sử dụng',
    lastUpdated: 'Cập nhật lần cuối',
    overview: 'Tổng quan',
    termsOverview: 'Cảm ơn bạn đã sử dụng Biteo. Các Điều khoản Sử dụng này ("Điều khoản") quy định quyền và nghĩa vụ của bạn khi sử dụng ứng dụng và dịch vụ của Biteo.',
    importantNotice: 'Lưu ý quan trọng',
    importantNoticeText: 'Bằng việc tiếp tục sử dụng ứng dụng Biteo, bạn xác nhận rằng bạn đã đọc, hiểu và đồng ý với các Điều khoản Sử dụng này.',
    needMoreHelp: 'Cần hỗ trợ thêm?',
    biteoTeamReady: 'Đội ngũ Biteo luôn sẵn sàng giải đáp mọi thắc mắc của bạn',
    contactNow: 'Liên hệ ngay',

    // Privacy Page
    privacyTitle: 'Chính sách Bảo mật',
    privacyOverview: 'Biteo cam kết bảo vệ thông tin cá nhân của bạn. Chính sách Bảo mật này giải thích cách chúng tôi thu thập, sử dụng, chia sẻ và bảo vệ thông tin của bạn.',
    privacySupport: 'Cần hỗ trợ về bảo mật?',

    // Partner Policy Page
    partnerPolicy: 'Chính sách Đối tác',
    partnerPolicyTitle: 'Cùng Biteo phát triển',
    partnerPolicyDesc: 'Khám phá các cơ hội hợp tác với Biteo và tham gia xây dựng hệ sinh thái số toàn diện',
    policyForPartners: 'Chính sách dành cho Đối tác',
    whyChooseBiteo: 'Tại sao chọn Biteo?',
    growth: 'Tăng trưởng',
    growthDesc: '500K+ người dùng đang chờ kết nối với bạn',
    safe: 'An toàn',
    safeDesc: 'Hệ thống bảo mật và hỗ trợ 24/7',
    flexible: 'Linh hoạt',
    flexibleDesc: 'Làm việc theo lịch trình của riêng bạn',
    reputable: 'Uy tín',
    reputableDesc: 'Thương hiệu được tin tưởng trên toàn quốc',
    readyPartner: 'Sẵn sàng trở thành Đối tác Biteo?',
    contactForAdvice: 'Liên hệ ngay để được tư vấn và bắt đầu hành trình cùng Biteo',
    contactConsult: 'Liên hệ tư vấn',
    registerNow: 'Đăng ký ngay',
    ctv: 'Cộng tác viên (CTV)',
    ctvDesc: 'Kiếm thêm thu nhập bằng cách giới thiệu dịch vụ và hỗ trợ người dùng.',
    unlimitedIncome: 'Không giới hạn thu nhập',
    flexibleTime: 'Linh hoạt thời gian',
    noCapital: 'Không cần vốn',
    freeTraining: 'Được đào tạo miễn phí',
    registerCTV: 'Đăng ký CTV',
    registerStaff: 'Đăng ký nhân viên',
    incomePerOrder: 'Thu nhập theo đơn hàng',
    flexibleSchedule: 'Lịch làm việc linh hoạt',
    workInsurance: 'Bảo hiểm khi làm việc',
    professionalTraining: 'Đào tạo chuyên nghiệp',
    businessPartners: 'Đối tác kinh doanh',
    businessPartnersDesc: 'Đưa sản phẩm và dịch vụ của bạn đến hàng triệu khách hàng Biteo.',
    reachNewCustomers: 'Tiếp cận khách hàng mới',
    modernTools: 'Công cụ quản lý hiện đại',
    marketingSupport: 'Hỗ trợ marketing',
    detailedReports: 'Báo cáo chi tiết',
    contactCooperation: 'Liên hệ hợp tác',
    partnerRights: 'Quyền lợi của Đối tác',
    partnerRightsText: 'Đối tác Biteo được hưởng các quyền lợi bao gồm: hoa hồng cạnh tranh, hỗ trợ marketing, công cụ quản lý hiện đại, đào tạo chuyên nghiệp và hỗ trợ kỹ thuật 24/7.',
    partnerObligations: 'Nghĩa vụ của Đối tác',
    partnerObligationsText: 'Đối tác cam kết cung cấp dịch vụ chất lượng, tuân thủ quy định của Biteo, bảo mật thông tin khách hàng.',
    paymentSettlement: 'Thanh toán và Settlement',
    paymentSettlementText: 'Thanh toán được thực hiện theo chu kỳ quy định. Đối tác có thể theo dõi doanh thu qua hệ thống.',
    qualityRating: 'Đánh giá và Chất lượng',
    qualityRatingText: 'Biteo áp dụng hệ thống đánh giá để đảm bảo chất lượng dịch vụ.',
    privacyData: 'Bảo mật và Dữ liệu',
    privacyDataText: 'Đối tác cam kết bảo mật mọi thông tin khách hàng và không sử dụng dữ liệu cho mục đích cá nhân.',
    terminateCooperation: 'Chấm dứt Hợp tác',
    terminateCooperationText: 'Mỗi bên có thể chấm dứt hợp tác với thông báo trước 30 ngày.',

    // Registration Pages
    registrationTitle: 'Đăng ký',
    registrationSubtitle: 'Điền thông tin để đăng ký',
    selectRole: 'Chọn vai trò',
    roleShopper: 'Nhân viên đi chợ hộ',
    roleAffiliate: 'Cộng tác viên',
    roleStore: 'Cửa hàng',
    roleCreator: 'Creator/Tiếp thị',
    personalInfo: 'Thông tin cá nhân',
    storeInfo: 'Thông tin cửa hàng',
    workArea: 'Khu vực làm việc',
    selectProvince: 'Chọn Tỉnh/Thành phố',
    selectDistrict: 'Chọn Quận/Huyện',
    selectWard: 'Chọn Phường/Xã',
    workingHours: 'Giờ làm việc',
    fullTime: 'Toàn thời gian',
    partTime: 'Bán thời gian',
    agreeTermsLabel: 'Tôi đồng ý với Điều khoản sử dụng và Chính sách bảo mật',
    shopName: 'Tên cửa hàng',
    shopType: 'Loại cửa hàng',
    restaurant: 'Nhà hàng',
    cafe: 'Quán cà phê',
    hotel: 'Khách sạn',
    supermarket: 'Siêu thị mini',
    specialty: 'Cửa hàng đặc sản',
    otherShop: 'Khác',
    taxCode: 'Mã số thuế',
    bankAccount: 'Số tài khoản',
    bankName: 'Tên ngân hàng',
    uploadDocuments: 'Tải lên tài liệu',
    driversLicense: 'GPLX (ảnh chụp)',
    idCard: 'CMND/CCCD',
    businessLicense: 'Giấy phép kinh doanh',
    preview: 'Xem trước',
    experience: 'Kinh nghiệm',
    noExperience: 'Chưa có kinh nghiệm',
    under1Year: 'Dưới 1 năm',
    over1Year: 'Trên 1 năm',
    whyJoinBiteo: 'Tại sao nên tham gia Biteo?',
    extraIncome: 'Thu nhập thêm',
    extraIncomeDesc: 'Kiếm thêm thu nhập từ việc giới thiệu dịch vụ và hỗ trợ người dùng trong khu vực của bạn.',
    support247: 'Hỗ trợ 24/7',
    support247Desc: 'Đội ngũ Biteo luôn sẵn sàng hỗ trợ bạn mọi lúc mọi nơi qua hotline và chat.',
    flexibleWork: 'Làm việc linh hoạt',
    flexibleWorkDesc: 'Bạn tự quyết định thời gian và khu vực làm việc phù hợp với lịch trình của mình.',
    training: 'Đào tạo miễn phí',
    trainingDesc: 'Được tham gia các khóa đào tạo chuyên nghiệp để nâng cao kỹ năng phục vụ.',
    dateOfBirth: 'Ngày sinh',
    motivation: 'Lý do bạn muốn tham gia',
    motivationPlaceholder: 'Chia sẻ với chúng tôi về động lực của bạn...',
    year: 'năm',
    watch: 'Xem',
    watchDesc: 'Video ngắn và nội dung thú vị',
    eat: 'Ăn',
    eatDesc: 'Khám phá ẩm thực quanh bạn',
    go: 'Đi',
    goDesc: 'Khám phá và đặt chuyến đi',
    buy: 'Mua',
    buyDesc: 'Mua sắm và đi chợ hộ',
    everythingYouNeed: 'Mọi thứ bạn cần, trong một trải nghiệm liền mạch.',
    allServicesConnected: 'Tất cả dịch vụ được kết nối và tích hợp hoàn hảo trong một ứng dụng duy nhất',

    // CTV Page
    ctvRegisterTitle: 'Đăng ký làm CTV',
    ctvHeroTitle: 'Trở thành CTV của Biteo ngay hôm nay',
    ctvHeroDesc: 'Kiếm thêm thu nhập dễ dàng, linh hoạt với công việc CTV tại Biteo. Không cần vốn, không rủi ro!',
    ctvUnlimitedIncome: 'Thu nhập không giới hạn',
    ctvUnlimitedIncomeDesc: 'Hoa hồng hấp dẫn từ mỗi đơn hàng thành công',
    ctvFlexibleTime: 'Linh hoạt về thời gian',
    ctvFlexibleTimeDesc: 'Làm việc mọi lúc mọi nơi, chỉ cần có điện thoại',
    ctvNoCapital: 'Không cần vốn',
    ctvNoCapitalDesc: 'Không rủi ro, không cần đầu tư ban đầu',
    ctvGrowth: 'Cơ hội thăng tiến',
    ctvGrowthDesc: 'Lộ trình phát triển rõ ràng từ CTV lên quản lý',
    ctvTraining: 'Đào tạo chuyên nghiệp',
    ctvTrainingDesc: 'Được hỗ trợ kiến thức và kỹ năng bán hàng',
    ctvCommunity: 'Cộng đồng gắn kết',
    ctvCommunityDesc: 'Gặp gỡ, kết nối với hàng nghìn CTV trên toàn quốc',
    ctvProvinces: 'Tỉnh thành',
    ctvSatisfied: 'Hài lòng',
    ctvSuccessTitle: 'Đăng ký thành công!',
    ctvSuccessDesc: 'Cảm ơn bạn đã đăng ký trở thành CTV của Biteo. Chúng tôi sẽ liên hệ với bạn trong 24 giờ tới để hướng dẫn các bước tiếp theo.',
    ctvRegisterNow: 'Đăng ký ngay',
    ctvRegisterDesc: 'Điền thông tin bên dưới để chúng tôi liên hệ với bạn',
    ctvFullName: 'Họ và tên',
    ctvPhone: 'Số điện thoại',
    ctvEmail: 'Email',
    ctvAddress: 'Địa chỉ',
    ctvAddressPlaceholder: 'Quận/Huyện, Tỉnh/Thành phố',
    ctvMotivation: 'Lý do tham gia',
    ctvMotivationPlaceholder: 'Chia sẻ với chúng tôi về động lực của bạn...',
    ctvProcessing: 'Đang xử lý...',
    ctvTermsAgree: 'Bằng việc đăng ký, bạn đồng ý với Điều khoản sử dụng và Chính sách bảo mật',

    // Creator Page
    creatorHeroTitle: 'Trở thành Creator cùng Biteo',
    creatorHeroDesc: 'Sáng tạo nội dung, chia sẻ đam mê và kiếm thu nhập cùng Biteo. Gia nhập đội ngũ Creator để lan tỏa giá trị đến hàng triệu người dùng.',
    creatorSuccessTitle: 'Đăng ký thành công!',
    creatorSuccessDesc: 'Cảm ơn bạn đã đăng ký trở thành Creator/Tiếp thị của Biteo. Đội ngũ Marketing sẽ liên hệ với bạn trong 24 giờ tới.',
    creatorRegisterTitle: 'Đăng ký Creator',
    creatorRegisterDesc: 'Điền thông tin của bạn để chúng tôi liên hệ',
    creatorNickname: 'Tên hiển thị / Nickname',
    creatorNicknamePlaceholder: 'Tên Creator của bạn',
    creatorPlatform: 'Nền tảng hoạt động',
    creatorAccountUrl: 'Link tài khoản',
    creatorFollowers: 'Số lượng người theo dõi',
    creatorFollowersPlaceholder: 'Chọn số lượng followers',
    creatorOver500k: 'Trên 500,000',
    creatorContentType: 'Loại nội dung chính',
    creatorContentTypePlaceholder: 'Chọn loại nội dung',
    creatorFoodReview: 'Review ẩm thực',
    creatorLifestyle: 'Phong cách sống',
    creatorShopping: 'Mua sắm',
    creatorCooking: 'Nấu ăn / Recipe',
    creatorVlog: 'Vlog / Kinh nghiệm',
    creatorOther: 'Khác',
    creatorMotivation: 'Tại sao bạn muốn trở thành Creator của Biteo?',
    creatorMotivationPlaceholder: 'Chia sẻ về định hướng và mong muốn của bạn...',
    creatorTermsAgree: 'Bằng việc đăng ký, bạn đồng ý với Điều khoản Creator và Chính sách bảo mật',
    creatorViews: 'Lượt xem',
    creatorOrders: 'Đơn hàng',
    creators: 'Creator',
    creatorIncome: 'Thu nhập không giới hạn',
    creatorIncomeDesc: 'Kiếm hoa hồng từ mỗi đơn hàng thành công',
    creatorFlexible: 'Thời gian linh hoạt',
    creatorFlexibleDesc: 'Làm việc theo lịch trình của riêng bạn',
    creatorSupport: 'Hỗ trợ 24/7',
    creatorSupportDesc: 'Đội ngũ Biteo luôn sẵn sàng hỗ trợ',
    creatorTools: 'Công cụ sáng tạo',
    creatorToolsDesc: 'Truy cập công cụ quản lý và phân tích',
    creatorCommunity: 'Cộng đồng Creator',
    creatorCommunityDesc: 'Kết nối với hàng nghìn Creator khác',

    // Store Page
    storeHeroTitle: 'Trở thành Đối tác Cửa hàng cùng Biteo',
    storeHeroDesc: 'Mở rộng kinh doanh của bạn với nền tảng Biteo. Tiếp cận hàng triệu khách hàng và tăng doanh thu một cách dễ dàng.',
    storeSuccessTitle: 'Đăng ký thành công!',
    storeSuccessDesc: 'Cảm ơn bạn đã đăng ký hợp tác cùng Biteo. Đội ngũ kinh doanh sẽ liên hệ với bạn trong 24 giờ tới để trao đổi chi tiết.',
    storeRegisterTitle: 'Đăng ký hợp tác',
    storeRegisterDesc: 'Điền thông tin cửa hàng của bạn để chúng tôi liên hệ',
    storeName: 'Tên cửa hàng',
    storeNamePlaceholder: 'Nhập tên cửa hàng của bạn',
    storeOwnerName: 'Họ và tên chủ cửa hàng',
    storeOwnerNamePlaceholder: 'Nhập họ và tên của bạn',
    storePhone: 'Số điện thoại',
    storeEmail: 'Email',
    storeAddress: 'Địa chỉ cửa hàng',
    storeAddressPlaceholder: 'Số nhà, Đường, Quận/Huyện, Tỉnh/Thành phố',
    storeType: 'Loại cửa hàng',
    storeTypePlaceholder: 'Chọn loại cửa hàng',
    storeSupermarket: 'Siêu thị / Mini mart',
    storeGrocery: 'Cửa hàng tạp hóa',
    storeOrganic: 'Cửa hàng thực phẩm hữu cơ',
    storeSpecialty: 'Cửa hàng chuyên biệt',
    storeRestaurant: 'Nhà hàng / Quán ăn',
    storeOther: 'Khác',
    storeTaxCode: 'Mã số kinh doanh',
    storeTaxCodePlaceholder: 'Mã số thuế / ĐKKD',
    storeIntro: 'Giới thiệu về cửa hàng của bạn',
    storeIntroPlaceholder: 'Chia sẻ về cửa hàng của bạn, sản phẩm chủ lực, điểm mạnh...',
    storeProcessing: 'Đang xử lý...',
    storeRegisterBtn: 'Đăng ký hợp tác',
    storeTermsAgree: 'Bằng việc đăng ký, bạn đồng ý với Điều khoản hợp tác và Chính sách bảo mật',
    storeBusinesses: 'Cửa hàng',
    storeCustomers: 'Khách hàng',
    storeIncreaseRevenue: 'Tăng doanh thu',
    storeIncreaseRevenueDesc: 'Tiếp cận hàng triệu khách hàng mới',
    storeModernTools: 'Công cụ hiện đại',
    storeModernToolsDesc: 'Quản lý cửa hàng dễ dàng với Biteo',
    storeMarketing: 'Hỗ trợ Marketing',
    storeMarketingDesc: 'Công cụ quảng cáo và khuyến mãi',
    storeReports: 'Báo cáo chi tiết',
    storeReportsDesc: 'Theo dõi doanh thu và thống kê',

    // Discover Local Page
    discoverHero: 'Khám phá địa phương',
    discoverTitle: 'Khám phá thế giới quanh bạn',
    discoverDesc: 'Tìm kiếm những địa điểm, dịch vụ và trải nghiệm đặc sắc ngay trong khu vực bạn sinh sống. Từ quán cà phê yêu thích đến những góc check-in đẹp.',
    discoverNow: 'Khám phá ngay',
    findNearMe: 'Tìm gần tôi',
    locations: 'Địa điểm',
    reviews: 'Reviews',
    categories2: 'Loại hình',
    discoverFeatures: 'Tính năng nổi bật',
    exploreAround: 'Khám phá xung quanh',
    exploreAroundDesc: 'Tìm kiếm những địa điểm thú vị, dịch vụ tiện ích ngay trong khu vực bạn sinh sống.',
    diverseLocations: 'Địa điểm đa dạng',
    diverseLocationsDesc: 'Từ công viên, quán cà phê đến các dịch vụ làm đẹp, giải trí - có tất cả trong Biteo.',
    smartSearch: 'Tìm kiếm thông minh',
    smartSearchDesc: 'Lọc theo loại hình, khoảng cách, đánh giá để tìm địa điểm phù hợp nhất.',
    realReview: 'Review thực tế',
    realReviewDesc: 'Xem hình ảnh và đánh giá từ người dùng thật, giúp bạn yên tâm khi đến.',
    accurateDirections: 'Chỉ đường chính xác',
    accurateDirectionsDesc: 'Dẫn đường đến địa điểm với bản đồ chi tiết và chỉ đường turn-by-turn.',
    saveFavorites: 'Lưu yêu thích',
    saveFavoritesDesc: 'Bookmark những địa điểm yêu thích để ghé thăm lần sau.',
    categoryTitle: 'Danh mục địa điểm',
    placesNearYou: 'Địa điểm gần bạn',
    seeAll: 'Xem tất cả',
    highlights: 'Điểm đến nổi bật',
    discoverWorld: 'Khám phá thế giới quanh bạn!',
    discoverWorldDesc: 'Mở ứng dụng Biteo và bắt đầu hành trình khám phá những địa điểm thú vị, dịch vụ tiện ích ngay trong khu vực bạn sống.',
    downloadIOS: 'Tải trên iOS',
    downloadAndroid: 'Tải trên Android',

    // Grocery Page
    groceryHero: 'Đi chợ hộ',
    groceryTitle: 'Chợ hộ thông minh, tiết kiệm thời gian',
    groceryDesc: 'Mua thực phẩm và nhu yếu phẩm nhanh chóng, tiện lợi ngay tại nơi bạn sống. Hàng tươi sạch, giao tận nơi, không cần ra chợ.',
    orderNow: 'Đặt hàng ngay',
    scheduleDelivery: 'Đặt lịch giao hàng',
    products: 'Sản phẩm',
    orders: 'Đơn hàng',
    areas: 'Khu vực',
    fastDelivery: 'Giao nhanh',
    howItWorks: 'Cách thức hoạt động',
    selectProducts: 'Chọn sản phẩm',
    selectProductsDesc: 'Duyệt và chọn thực phẩm bạn cần từ danh mục đa dạng',
    confirmOrder: 'Xác nhận đơn hàng',
    confirmOrderDesc: 'Kiểm tra giỏ hàng và xác nhận với thông tin giao hàng',
    receiveOrder: 'Nhận hàng',
    receiveOrderDesc: 'Người mua hộ sẽ giao tận nơi đúng thời gian bạn chọn',
    groceryFeatures: 'Tính năng nổi bật',
    easySelect: 'Chọn hàng dễ dàng',
    easySelectDesc: 'Duyệt danh mục thực phẩm đầy đủ, xem giá cả minh bạch và chọn sản phẩm yêu thích.',
    fastDelivery2: 'Giao hàng nhanh',
    fastDelivery2Desc: 'Nhận hàng trong 2-4 giờ hoặc đặt lịch giao hàng phù hợp với thời gian biểu của bạn.',
    freeDelivery: 'Miễn phí giao hàng',
    freeDeliveryDesc: 'Miễn phí giao hàng cho đơn từ 200,000đ. Phí giao hàng chỉ từ 15,000đ.',
    freshFood: 'Hàng tươi sạch',
    freshFoodDesc: 'Cam kết 100% hàng tơi, nguồn gốc rõ ràng từ các nhà cung cấp uy tín.',
    easyReturn: 'Đổi trả dễ dàng',
    easyReturnDesc: 'Chính sách đổi trả trong 24 giờ nếu sản phẩm không đúng yêu cầu.',
    repeatBuy: 'Mua lặp lại',
    repeatBuyDesc: 'Lưu danh sách mua thường xuyên, đặt hàng chỉ với một chạm.',
    productCategories: 'Danh mục sản phẩm',
    popularProducts: 'Sản phẩm phổ biến',
    startShopping: 'Bắt đầu mua sắm ngay hôm nay!',
    startShoppingDesc: 'Tải ứng dụng Biteo và trải nghiệm dịch vụ đi chợ hộ tiện lợi. Đơn hàng đầu tiên được miễn phí giao hàng!',

    // Shopping Page
    shoppingHero: 'Mua sắm',
    shoppingTitle: 'Đặc sản Việt Nam trong tầm tay',
    shoppingDesc: 'Khám phá và mua sắm đặc sản địa phương, sản phẩm OCOP và những sản phẩm được tuyển chọn từ khắp Việt Nam.',
    shopNow: 'Mua sắm ngay',
    viewOffers: 'Xem ưu đãi',
    shopProducts: 'Sản phẩm',
    sellers: 'Nhà bán hàng',
    shoppingFeatures: 'Tính năng nổi bật',
    localSpecialties: 'Đặc sản địa phương',
    localSpecialtiesDesc: 'Khám phá và mua sắm đặc sản từ khắp Việt Nam, từ bánh tráng Trảng Bàng đến cà phê Buôn Ma Thuột.',
    fastDelivery3: 'Giao hàng nhanh',
    fastDelivery3Desc: 'Nhận hàng trong 24-48h với hệ thống logistics phủ khắp 63 tỉnh thành.',
    qualityProducts: 'Sản phẩm chất lượng',
    qualityProductsDesc: 'Tất cả sản phẩm được kiểm duyệt, đảm bảo chất lượng và nguồn gốc rõ ràng.',
    securePayment: 'Thanh toán an toàn',
    securePaymentDesc: 'Nhiều phương thức thanh toán, bảo mật thông tin tuyệt đối.',
    favorites: 'Yêu thích & Đánh giá',
    favoritesDesc: 'Lưu sản phẩm yêu thích, xem đánh giá từ người mua thật.',
    greatOffers: 'Ưu đãi hấp dẫn',
    greatOffersDesc: 'Mã giảm giá, khuyến mãi định kỳ và chương trình tích điểm thưởng.',
    productCategories2: 'Danh mục sản phẩm',
    northSpecialties: 'Đặc sản miền Bắc',
    centralSpecialties: 'Đặc sản miền Trung',
    southSpecialties: 'Đặc sản miền Nam',
    featuredProducts: 'Sản phẩm nổi bật',
    topSellers: 'Nhà bán hàng xuất sắc',
    shopNow2: 'Mua sắm đặc sản ngay hôm nay!',
    shopNow2Desc: 'Tải ứng dụng Biteo để khám phá kho đặc sản phong phú từ khắp Việt Nam. Nhận ngay ưu đãi 20% cho đơn hàng đầu tiên!',

    // Travel Page
    travelHero: 'Du lịch',
    travelTitle: 'Khám phá Việt Nam một cách trọn vẹn',
    travelDesc: 'Đặt phòng, tìm điểm đến và lên kế hoạch cho những hành trình đáng nhớ. Tất cả trong một ứng dụng với giá tốt nhất.',
    exploreNow: 'Khám phá ngay',
    planTrip: 'Lên kế hoạch',
    destinations: 'Điểm đến',
    hotels: 'Khách sạn',
    travelers: 'Du khách',
    travelFeatures: 'Tính năng nổi bật',
    smartSearch2: 'Tìm kiếm thông minh',
    smartSearch2Desc: 'Khám phá điểm đến với bộ lọc theo loại hình du lịch, ngân sách, địa điểm.',
    diverseDestinations: 'Địa điểm đa dạng',
    diverseDestinationsDesc: 'Từ biển đảo, núi rừng đến các thành phố hiện đại - có tất cả trong Biteo.',
    bookHotel: 'Đặt phòng khách sạn',
    bookHotelDesc: 'So sánh giá, xem đánh giá và đặt phòng khách sạn với giá tốt nhất.',
    bookTicket: 'Đặt vé du lịch',
    bookTicketDesc: 'Mua vé máy bay, vé tàu, tour du lịch trực tiếp trên ứng dụng.',
    travelGuide: 'Cẩm nang du lịch',
    travelGuideDesc: 'Khám phá kinh nghiệm du lịch, địa điểm check-in, ẩm thực địa phương.',
    saveFavorites2: 'Lưu yêu thích',
    saveFavorites2Desc: 'Lưu lại những điểm đến mơ ước để lên kế hoạch cho chuyến đi tiếp theo.',
    popularDestinations: 'Điểm đến phổ biến',
    travelTypes: 'Loại hình du lịch',
    beachTravel: 'Du lịch biển',
    mountainTravel: 'Du lịch núi',
    culturalTravel: 'Du lịch văn hóa',
    adventure: 'Adventure',
    familyTravel: 'Du lịch gia đình',
    foodTour: 'Food tour',
    nextTrip: 'Sẵn sàng cho chuyến đi tiếp theo?',
    nextTripDesc: 'Lên kế hoạch, đặt phòng và khám phá những điểm đến tuyệt vời cùng Biteo. Đặt ngay hôm nay để nhận ưu đãi đặc biệt!',

    // Culinary Page
    culinaryHero: 'Ẩm thực',
    culinaryTitle: 'Khám phá hương vị khắp Việt Nam',
    culinaryDesc: 'Tìm kiếm nhà hàng, quán ăn, quán cà phê và những hương vị đặc sắc quanh bạn. Đặt bàn online, xem đánh giá thực tế từ cộng đồng.',
    findFoodNear: 'Tìm quán ăn gần đây',
    specificSearch: 'Tìm kiếm cụ thể',
    restaurants: 'Nhà hàng & quán ăn',
    culinaryFeatures: 'Tính năng nổi bật',
    smartSearch3: 'Tìm kiếm thông minh',
    smartSearch3Desc: 'Tìm nhà hàng, quán ăn gần bạn với bộ lọc đa dạng theo loại món, khoảng cách, đánh giá.',
    accurateLocation: 'Định vị chính xác',
    accurateLocationDesc: 'Xem vị trí nhà hàng trên bản đồ, chỉ đường đến địa điểm nhanh chóng.',
    realRatings: 'Đánh giá thực tế',
    realRatingsDesc: 'Hàng triệu đánh giá từ người dùng thật, giúp bạn chọn đúng nơi ăn.',
    bookOnline: 'Đặt bàn trực tuyến',
    bookOnlineDesc: 'Đặt bàn trước tại nhà hàng yêu thích, không cần gọi điện chờ đợi.',
    transparentInfo: 'Thông tin minh bạch',
    transparentInfoDesc: 'Xem giá cả, thực đơn, giờ mở cửa rõ ràng trước khi quyết định.',
    saveFavorites3: 'Lưu yêu thích',
    saveFavorites3Desc: 'Tạo danh sách quán ăn yêu thích, chia sẻ với bạn bè dễ dàng.',
    cuisines: 'Ẩm thực đa dạng',
    restaurants2: 'Nhà hàng nổi bật',
    featured: 'Được yêu thích',
    hungryNow: 'Đói bụng? Tìm ngay quán ăn!',
    hungryNowDesc: 'Mở ứng dụng Biteo, tìm quán ăn gần bạn, đặt bàn và thưởng thức những món ngon.',

    // Video Page
    videoHero: 'Video giải trí',
    videoTitle: 'Giải trí không giới hạn, mọi lúc mọi nơi',
    videoDesc: 'Khám phá kho video giải trí phong phú từ cộng đồng creator Việt Nam. Video ngắn, phim ngắn, nội dung địa phương - tất cả trong một ứng dụng.',
    downloadApp: 'Tải ứng dụng',
    tryNow: 'Xem thử ngay',
    views: 'Lượt xem',
    videos: 'Video',
    creators: 'Creator',
    users2: 'Người dùng',
    videoFeatures: 'Tính năng nổi bật',
    diverseContent: 'Nội dung đa dạng',
    diverseContentDesc: 'Từ video giải trí, phim ngắn đến nội dung địa phương phong phú từ khắp Việt Nam.',
    creativeCommunity: 'Cộng đồng sáng tạo',
    creativeCommunityDesc: 'Kết nối với hàng triệu creator Việt Nam, chia sẻ và khám phá nội dung độc đáo.',
    smoothExperience: 'Mượt mà trên mọi thiết bị',
    smoothExperienceDesc: 'Trải nghiệm xem video liền mạch trên điện thoại, tablet và TV thông minh.',
    personalizedContent: 'Nội dung được cá nhân hóa',
    personalizedContentDesc: 'Thuật toán AI học sở thích của bạn, gợi ý video phù hợp mỗi ngày.',
    easyShare: 'Chia sẻ dễ dàng',
    easyShareDesc: 'Lưu, chia sẻ video yêu thích lên mạng xã hội chỉ với một chạm.',
    unlimitedFavorites: 'Yêu thích không giới hạn',
    unlimitedFavoritesDesc: 'Tạo bộ sưu tập video riêng, xem lại bất cứ khi nào bạn muốn.',
    popularCategories: 'Danh mục phổ biến',
    trendingCreators: 'Creator nổi bật',
    followers: 'followers',
    exploreVideo: 'Sẵn sàng khám phá thế giới video?',
    exploreVideoDesc: 'Tải ngay ứng dụng Biteo và bắt đầu hành trình khám phá kho video giải trí đồ sộ từ cộng đồng creator Việt Nam.',

    // Discover categories
    catCafe: 'Quán cà phê',
    catPark: 'Công viên',
    catRestaurant: 'Nhà hàng',
    catSpa: 'Spa & Salon',
    catGym: 'Phòng gym',
    catShop: 'Shop',
    turtleLake: '�ịa điểm check-in nổi tiếng',
    benThanhMarket: 'Chợ truyền thống đặc sắc',
    nguyenHueStreet: 'Khu vực sôi động về đêm',
    hcmcMuseum: 'Di sản văn hóa lịch sử',

    // Grocery categories
    catVegetables: 'Rau củ quả',
    catMeat: 'Thịt tươi',
    catSeafood: 'Hải sản',
    catDairy: 'Trứng & Sữa',
    catSpices: 'Gia vị',
    catDry: 'Đồ khô',

    // Shopping categories
    catNorth: 'Đặc sản miền Bắc',
    catCentral: 'Đặc sản miền Trung',
    catSouth: 'Đặc sản miền Nam',
    catOCOP: 'OCOP',
    catAgri: 'Nông sản',
    catCraft: 'Thủ công mỹ nghệ',
    shopBanhtrang: 'Bánh Tráng Trảng Bàng',
    shopCoffee: 'Cà Phê Arabica Cầu Đất',
    shopBanhda: 'Bánh Đa Cua Hải Phòng',
    shopNuocmam: 'Nước Mắm Phú Quốc',
    shopVungdat: 'Vùng Đất Đặc Sản',
    shopOCOPStore: 'OCOP Store',
    shopNongsan: 'Nông Sản Việt',
    shopBaMien: '�ặc Sản 3 Miền',

    // Travel destinations
    destDanang: 'Đà Nẵng',
    destDanangType: 'Biển & Núi',
    destPhuquoc: 'Phú Quốc',
    destPhuquocType: 'Đảo',
    destSapa: 'Sapa',
    destSapaType: 'Núi',
    destHoian: 'Hội An',
    destHoianType: 'Văn hóa',
    destNhatrang: 'Nha Trang',
    destNhatrangType: 'Biển',
    destHagiang: 'Hà Giang',
    destHagiangType: 'Núi',

    // Culinary
    catVietnam: 'Việt Nam',
    catJapan: 'Nhật Bản',
    catKorea: 'Hàn Quốc',
    catItaly: 'Ý',
    catChina: 'Trung Hoa',
    catThailand: 'Thái Lan',
    restBepMe: 'Bếp Mẹ Mạnh',
    restVietnam: 'Việt Nam',
    restSushi: 'Sushi King',
    restJapan: 'Nhật Bản',
    restKBBQ: 'KBBQ House',
    restKorea: 'Hàn Quốc',
    restPizza: 'Pizza Milano',
    restItaly: 'Ý',

    // Video categories
    catShortFilm: 'Phim ngắn',
    catVideoFood: 'Ẩm thực',
    catVideoTravel: 'Du lịch',
    catMusic: 'Âm nhạc',
    catComedy: 'Hài hước',
    catEducation: 'Giáo dục',
    creatorVietnam: 'Vietnam Travel',
    creatorFood: 'Food Paradise',
    creatorComedy: 'Comedy VN',
    creatorTravelKid: 'Travel Kid',
  },
  en: {
    // Header
    menu: 'Menu',
    search: 'Search',
    registerConsultation: 'Register Consultation',
    supportCenter: 'Support Center',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    closeMenu: 'Close menu',
    openMenu: 'Open menu',
    downloadApp: 'Download App',
    joinBiteo: 'Join Biteo',
    shopperStaff: 'Shopper Staff',
    shoppingAssistant: 'Shopping Assistant',
    biteoAffiliate: 'Biteo Affiliate',
    collaborator: 'Collaborator',
    registerStore: 'Register Store',
    businessPartner: 'Business Partnership',
    creatorMarketing: 'Creator/Marketing',
    contentMarketing: 'Content & Marketing',
    becomePartner: 'Become a Partner',

    // Hero
    heroBadge: 'Discover vibrant life with Biteo',
    heroTitle: 'Connect Community',
    heroSubtitle: 'Share joy together.',
    heroDescription: 'From grocery shopping to ordering food and sharing interesting places with friends. All in one seamless experience.',
    downloadNow: 'Download Now',
    watchIntro: 'Watch Introduction',
    users: 'Users',
    rating: 'Rating',
    support: 'Support',

    // Feature Cards
    orderFood: 'Order Food',
    groceryShopping: 'Grocery Shopping',
    travel: 'Travel',
    explore: 'Explore',

    // Trust Bar
    ecosystemTitle: 'One Ecosystem – Many Needs',
    ecosystemSubtitle: 'All in one single app',
    video: 'Video',
    culinary: 'Culinary',
    shopping: 'Shopping',
    localExplore: 'Explore',

    // Stats Section
    techServingLife: 'Technology Serving Life.',
    statsDescription: 'Every feature of Biteo is designed for simplicity, convenience, and ease of use. We continuously improve the experience so users, businesses, and partners can connect quickly, use effectively, and together create a technology ecosystem for Vietnamese people.',
    multiService: 'Multi-Service',
    localConnect: 'Local Connection',
    seamlessExperience: 'Seamless Experience',
    opportunity: 'Opportunity for Everyone',

    // Service Ecosystem
    oneApp: 'One App.',
    millionExperiences: 'Millions of Experiences.',
    ecosystemDescription: 'With just one app, users can discover short videos, find dining spots, make reservations, book accommodations, shop local specialties, use grocery shopping services, and many other utilities.',
    discover: 'Discover',
    entertainmentVideo: 'Entertainment Video',
    entertainmentDesc: 'Discover short videos, local content, and exciting experiences every day.',
    culinaryDesc: 'Find restaurants, eateries, cafes, and distinctive flavors around you.',
    travelDesc: 'Explore destinations, book rooms, and plan memorable journeys.',
    shoppingDesc: 'Discover local specialties and curated products.',
    groceryDesc: 'Buy groceries and essentials quickly and conveniently right where you live.',
    localDiscoverTitle: 'Local Discovery',
    localDiscoverDesc: 'Find distinctive places, services, and experiences around you.',

    // Opportunities
    opportunitiesTitle: 'Create New',
    newOpportunities: 'Opportunities with Biteo',
    opportunitiesDesc: 'More than an app, Biteo creates opportunities for collaborators and partners across the country to participate in building a digital ecosystem.',
    collaborators: 'Collaborators',
    collabDesc: 'Join the ecosystem and generate additional income.',
    becomeCollaborator: 'Become a Collaborator',
    businessPartnerTitle: 'Business Partner',
    businessPartnerDesc: 'Bring your products and services to millions of customers.',
    registerPartner: 'Register as Partner',
    localPartner: 'Local Partner',
    localPartnerDesc: 'With Biteo, promote local economy and digital transformation.',
    learnMore: 'Learn More',

    // Business Section
    forBusiness: 'FOR BUSINESSES',
    bringBusinessCloser: 'Bring Local Business Closer to Customers',
    businessDesc: 'Biteo accompanies restaurants, cafes, hotels, homestays, specialty shops, mini supermarkets, and other business models in their digital transformation journey.',
    reachNewCustomers: 'Reach New Customers',
    increaseRevenue: 'Increase Revenue',
    manageEffectively: 'Manage Operations Effectively',
    buildDigitalBrand: 'Build Digital Brand',
    sustainableGrowth: 'Sustainable Development',
    becomeBiteoPartner: 'Become a Biteo Partner',
    businesses: 'Businesses',
    provinces: 'Provinces',
    appUsers: 'Users',

    // Support Section
    support: 'Support',
    supportTitle: 'Support',
    supportTitleHighlight: 'Center',
    supportDesc: 'Biteo team is always ready to support you 24/7. Contact us if you need help.',
    liveChat: 'Live Chat',
    liveChatDesc: 'Chat with support team 24/7',
    email: 'Email',
    emailDesc: 'Send support requests via email',
    responseIn24h: 'Response in 24h',
    hotline: 'Hotline',
    hotlineDesc: 'Call directly for consultation',
    faqCenter: 'FAQ Center',
    faqCenterDesc: 'Find answers quickly',
    alwaysUpdated: 'Always Updated',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Quick answers to common issues',
    contactSupport: 'Contact Support',
    faqQ1: 'How do I register as a Biteo collaborator?',
    faqA1: 'You can register directly at the collaborator registration page or contact hotline 0986498899.',
    faqQ2: 'Does Biteo support delivery nationwide?',
    faqA2: 'Currently, Biteo is expanding services in major provinces and cities.',
    faqQ3: 'I encounter issues when using the app?',
    faqA3: 'Contact hotline 0986498899 or send email to support@biteo.vn.',

    // Download App
    platformExperiences: 'One Platform, Every Experience.',
    downloadDesc: 'Discover, connect, and enjoy all utilities in one single app. Download now to start your experience.',
    downloadOn: 'Download on',
    availableOn: 'Available on',
    scanQR: 'Scan QR Code',
    scanQRDesc: 'to download the app',
    iosAndroid: 'iOS & Android',
    topRestaurants: 'Top Restaurants',
    nearYou: 'Near You',

    // Final CTA
    readyExperience: 'Ready to Experience Biteo?',
    ctaDesc: 'Join the Biteo ecosystem and discover a whole new way to connect with life.',
    exploreBiteo: 'Explore Biteo',

    // Footer
    aboutBiteo: 'About Biteo',
    contact: 'Contact',
    services: 'Services',
    registerBusiness: 'Register Business',
    supportCenter: 'Support Center',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    partnerPolicy: 'Partner Policy',
    footerDesc: 'Biteo – Multi-service technology platform connecting users, businesses, and partners in a comprehensive digital ecosystem.',
    biteo: 'Biteo',
    legal: 'Legal',
    partners: 'Partners',

    // Registration Pages
    register: 'Register',
    fullName: 'Full Name',
    phone: 'Phone Number',
    emailAddress: 'Email Address',
    address: 'Address',
    city: 'City/Province',
    district: 'District',
    ward: 'Ward/Commune',
    submit: 'Submit Registration',
    cancel: 'Cancel',
    required: 'Required',
    optional: 'Optional',
    success: 'Registration successful!',
    error: 'An error occurred. Please try again.',
    agreeTerms: 'I agree to the Terms of Use and Privacy Policy',

    // Common
    home: 'Home',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    save: 'Save',
    loading: 'Loading...',
    message: 'Message',
    subject: 'Subject',
    feedback: 'Product Feedback',
    report: 'Report Issue',
    other: 'Other',
    businessHours: 'Business Hours',
    office: 'Office',
    weekdays: 'Mon - Fri',

    // Terms Page
    termsTitle: 'Terms of Use',
    lastUpdated: 'Last updated',
    overview: 'Overview',
    termsOverview: 'Thank you for using Biteo. These Terms of Service ("Terms") govern your rights and obligations when using Biteo applications and services.',
    importantNotice: 'Important Notice',
    importantNoticeText: 'By continuing to use the Biteo app, you confirm that you have read, understood, and agreed to these Terms of Service.',
    needMoreHelp: 'Need more help?',
    biteoTeamReady: 'Biteo team is always ready to answer your questions',
    contactNow: 'Contact Now',

    // Privacy Page
    privacyTitle: 'Privacy Policy',
    privacyOverview: 'Biteo is committed to protecting your personal information. This Privacy Policy explains how we collect, use, share, and protect your information.',
    privacySupport: 'Need privacy support?',

    // Partner Policy Page
    partnerPolicy: 'Partner Policy',
    partnerPolicyTitle: 'Grow with Biteo',
    partnerPolicyDesc: 'Explore collaboration opportunities with Biteo and participate in building a comprehensive digital ecosystem',
    policyForPartners: 'Policy for Partners',
    whyChooseBiteo: 'Why choose Biteo?',
    growth: 'Growth',
    growthDesc: '500K+ users waiting to connect with you',
    safe: 'Safe',
    safeDesc: 'Security system and 24/7 support',
    flexible: 'Flexible',
    flexibleDesc: 'Work on your own schedule',
    reputable: 'Reputable',
    reputableDesc: 'Trusted brand nationwide',
    readyPartner: 'Ready to become a Biteo Partner?',
    contactForAdvice: 'Contact now for consultation and start your journey with Biteo',
    contactConsult: 'Contact for Consultation',
    registerNow: 'Register Now',
    ctv: 'Collaborator',
    ctvDesc: 'Earn extra income by referring services and supporting users.',
    unlimitedIncome: 'Unlimited income',
    flexibleTime: 'Flexible time',
    noCapital: 'No capital required',
    freeTraining: 'Free training',
    registerCTV: 'Register as Collaborator',
    registerStaff: 'Register as Staff',
    incomePerOrder: 'Income per order',
    flexibleSchedule: 'Flexible schedule',
    workInsurance: 'Work insurance',
    professionalTraining: 'Professional training',
    businessPartners: 'Business Partners',
    businessPartnersDesc: 'Bring your products and services to millions of Biteo customers.',
    reachNewCustomers: 'Reach new customers',
    modernTools: 'Modern management tools',
    marketingSupport: 'Marketing support',
    detailedReports: 'Detailed reports',
    contactCooperation: 'Contact for Cooperation',
    partnerRights: 'Partner Rights',
    partnerRightsText: 'Biteo partners enjoy competitive commissions, marketing support, modern management tools, professional training, and 24/7 technical support.',
    partnerObligations: 'Partner Obligations',
    partnerObligationsText: 'Partners commit to providing quality services, complying with Biteo regulations, and protecting customer information.',
    paymentSettlement: 'Payment & Settlement',
    paymentSettlementText: 'Payments are made according to the specified cycle. Partners can track revenue through the system.',
    qualityRating: 'Quality & Rating',
    qualityRatingText: 'Biteo applies a rating system to ensure service quality.',
    privacyData: 'Privacy & Data',
    privacyDataText: 'Partners commit to protecting all customer information and not using data for personal purposes.',
    terminateCooperation: 'Terminate Cooperation',
    terminateCooperationText: 'Either party may terminate cooperation with 30 days notice.',

    // Registration Pages
    registrationTitle: 'Register',
    registrationSubtitle: 'Fill in information to register',
    selectRole: 'Select role',
    roleShopper: 'Shopper Staff',
    roleAffiliate: 'Affiliate',
    roleStore: 'Store',
    roleCreator: 'Creator/Marketing',
    personalInfo: 'Personal Information',
    storeInfo: 'Store Information',
    workArea: 'Working Area',
    selectProvince: 'Select Province/City',
    selectDistrict: 'Select District',
    selectWard: 'Select Ward/Commune',
    workingHours: 'Working Hours',
    fullTime: 'Full-time',
    partTime: 'Part-time',
    agreeTermsLabel: 'I agree to the Terms of Use and Privacy Policy',
    shopName: 'Store Name',
    shopType: 'Store Type',
    restaurant: 'Restaurant',
    cafe: 'Cafe',
    hotel: 'Hotel',
    supermarket: 'Mini Supermarket',
    specialty: 'Specialty Store',
    otherShop: 'Other',
    taxCode: 'Tax Code',
    bankAccount: 'Bank Account',
    bankName: 'Bank Name',
    uploadDocuments: 'Upload Documents',
    driversLicense: 'Driver License',
    idCard: 'ID Card',
    businessLicense: 'Business License',
    preview: 'Preview',
    experience: 'Experience',
    noExperience: 'No experience',
    under1Year: 'Under 1 year',
    over1Year: 'Over 1 year',
    whyJoinBiteo: 'Why join Biteo?',
    extraIncome: 'Extra Income',
    extraIncomeDesc: 'Earn extra income from referring services and supporting users in your area.',
    support247: '24/7 Support',
    support247Desc: 'Biteo team is always ready to support you anytime via hotline and chat.',
    flexibleWork: 'Flexible Work',
    flexibleWorkDesc: 'You decide the time and area that suits your schedule.',
    training: 'Free Training',
    trainingDesc: 'Participate in professional training courses to improve service skills.',
    dateOfBirth: 'Date of Birth',
    motivation: 'Your motivation',
    motivationPlaceholder: 'Share with us about your motivation...',
    year: 'years',
    watch: 'Watch',
    watchDesc: 'Short videos and fun content',
    eat: 'Eat',
    eatDesc: 'Explore culinary around you',
    go: 'Go',
    goDesc: 'Explore and book trips',
    buy: 'Buy',
    buyDesc: 'Shopping and grocery',
    everythingYouNeed: 'Everything you need, in one seamless experience.',
    allServicesConnected: 'All services are connected and perfectly integrated in one single app',

    // CTV Page
    ctvRegisterTitle: 'Register as Collaborator',
    ctvHeroTitle: 'Become a Biteo Collaborator Today',
    ctvHeroDesc: 'Earn extra income easily with flexible CTV work at Biteo. No capital needed, no risk!',
    ctvUnlimitedIncome: 'Unlimited Income',
    ctvUnlimitedIncomeDesc: 'Attractive commissions from each successful order',
    ctvFlexibleTime: 'Flexible Time',
    ctvFlexibleTimeDesc: 'Work anytime, anywhere, just need a phone',
    ctvNoCapital: 'No Capital Required',
    ctvNoCapitalDesc: 'No risk, no initial investment needed',
    ctvGrowth: 'Growth Opportunities',
    ctvGrowthDesc: 'Clear development path from CTV to manager',
    ctvTraining: 'Professional Training',
    ctvTrainingDesc: 'Get support on knowledge and sales skills',
    ctvCommunity: 'Connected Community',
    ctvCommunityDesc: 'Meet and connect with thousands of CTVs nationwide',
    ctvProvinces: 'Provinces',
    ctvSatisfied: 'Satisfied',
    ctvSuccessTitle: 'Registration Successful!',
    ctvSuccessDesc: 'Thank you for registering as a Biteo CTV. We will contact you within 24 hours to guide you through the next steps.',
    ctvRegisterNow: 'Register Now',
    ctvRegisterDesc: 'Fill in your information below so we can contact you',
    ctvFullName: 'Full Name',
    ctvPhone: 'Phone Number',
    ctvEmail: 'Email',
    ctvAddress: 'Address',
    ctvAddressPlaceholder: 'District, City/Province',
    ctvMotivation: 'Reason for joining',
    ctvMotivationPlaceholder: 'Share with us about your motivation...',
    ctvProcessing: 'Processing...',
    ctvTermsAgree: 'By registering, you agree to the Terms of Use and Privacy Policy',

    // Creator Page
    creatorHeroTitle: 'Become a Creator with Biteo',
    creatorHeroDesc: 'Create content, share passion and earn income with Biteo. Join the Creator team to spread value to millions of users.',
    creatorSuccessTitle: 'Registration Successful!',
    creatorSuccessDesc: 'Thank you for registering as a Biteo Creator/Marketer. The Marketing team will contact you within 24 hours.',
    creatorRegisterTitle: 'Register as Creator',
    creatorRegisterDesc: 'Fill in your information for us to contact you',
    creatorNickname: 'Display Name / Nickname',
    creatorNicknamePlaceholder: 'Your Creator name',
    creatorPlatform: 'Active Platform',
    creatorAccountUrl: 'Account Link',
    creatorFollowers: 'Number of Followers',
    creatorFollowersPlaceholder: 'Select number of followers',
    creatorOver500k: 'Over 500,000',
    creatorContentType: 'Main Content Type',
    creatorContentTypePlaceholder: 'Select content type',
    creatorFoodReview: 'Food Review',
    creatorLifestyle: 'Lifestyle',
    creatorShopping: 'Shopping',
    creatorCooking: 'Cooking / Recipe',
    creatorVlog: 'Vlog / Experience',
    creatorOther: 'Other',
    creatorMotivation: 'Why do you want to become a Biteo Creator?',
    creatorMotivationPlaceholder: 'Share your direction and expectations...',
    creatorTermsAgree: 'By registering, you agree to the Creator Terms and Privacy Policy',
    creatorViews: 'Views',
    creatorOrders: 'Orders',
    creators: 'Creators',
    creatorIncome: 'Unlimited Income',
    creatorIncomeDesc: 'Earn commissions from each successful order',
    creatorFlexible: 'Flexible Schedule',
    creatorFlexibleDesc: 'Work on your own schedule',
    creatorSupport: '24/7 Support',
    creatorSupportDesc: 'Biteo team is always ready to support',
    creatorTools: 'Creative Tools',
    creatorToolsDesc: 'Access management and analytics tools',
    creatorCommunity: 'Creator Community',
    creatorCommunityDesc: 'Connect with thousands of other Creators',

    // Store Page
    storeHeroTitle: 'Become a Store Partner with Biteo',
    storeHeroDesc: 'Expand your business with the Biteo platform. Reach millions of customers and increase revenue easily.',
    storeSuccessTitle: 'Registration Successful!',
    storeSuccessDesc: 'Thank you for registering to partner with Biteo. The business team will contact you within 24 hours for detailed discussion.',
    storeRegisterTitle: 'Register Partnership',
    storeRegisterDesc: 'Fill in your store information for us to contact you',
    storeName: 'Store Name',
    storeNamePlaceholder: 'Enter your store name',
    storeOwnerName: 'Store Owner Full Name',
    storeOwnerNamePlaceholder: 'Enter your full name',
    storePhone: 'Phone Number',
    storeEmail: 'Email',
    storeAddress: 'Store Address',
    storeAddressPlaceholder: 'Street, District, City/Province',
    storeType: 'Store Type',
    storeTypePlaceholder: 'Select store type',
    storeSupermarket: 'Supermarket / Mini mart',
    storeGrocery: 'Grocery store',
    storeOrganic: 'Organic food store',
    storeSpecialty: 'Specialty store',
    storeRestaurant: 'Restaurant / Eatery',
    storeOther: 'Other',
    storeTaxCode: 'Business License Number',
    storeTaxCodePlaceholder: 'Tax Code / Business License',
    storeIntro: 'About Your Store',
    storeIntroPlaceholder: 'Share about your store, main products, strengths...',
    storeProcessing: 'Processing...',
    storeRegisterBtn: 'Register Partnership',
    storeTermsAgree: 'By registering, you agree to the Partnership Terms and Privacy Policy',
    storeBusinesses: 'Stores',
    storeCustomers: 'Customers',
    storeIncreaseRevenue: 'Increase Revenue',
    storeIncreaseRevenueDesc: 'Reach millions of new customers',
    storeModernTools: 'Modern Tools',
    storeModernToolsDesc: 'Manage your store easily with Biteo',
    storeMarketing: 'Marketing Support',
    storeMarketingDesc: 'Advertising and promotion tools',
    storeReports: 'Detailed Reports',
    storeReportsDesc: 'Track revenue and statistics',

    // Discover Local Page
    discoverHero: 'Discover Local',
    discoverTitle: 'Explore the World Around You',
    discoverDesc: 'Find distinctive places, services, and experiences right in your neighborhood. From favorite cafes to beautiful check-in spots.',
    discoverNow: 'Discover Now',
    findNearMe: 'Find Near Me',
    locations: 'Locations',
    reviews: 'Reviews',
    categories2: 'Categories',
    discoverFeatures: 'Key Features',
    exploreAround: 'Explore Around',
    exploreAroundDesc: 'Find interesting places and useful services right in your neighborhood.',
    diverseLocations: 'Diverse Locations',
    diverseLocationsDesc: 'From parks, cafes to beauty services, entertainment - all in Biteo.',
    smartSearch: 'Smart Search',
    smartSearchDesc: 'Filter by type, distance, ratings to find the most suitable locations.',
    realReview: 'Real Reviews',
    realReviewDesc: 'See photos and reviews from real users, helping you feel confident when visiting.',
    accurateDirections: 'Accurate Directions',
    accurateDirectionsDesc: 'Navigate to locations with detailed maps and turn-by-turn directions.',
    saveFavorites: 'Save Favorites',
    saveFavoritesDesc: 'Bookmark favorite places to visit next time.',
    categoryTitle: 'Location Categories',
    placesNearYou: 'Places Near You',
    seeAll: 'See All',
    highlights: 'Highlights',
    discoverWorld: 'Explore the World Around You!',
    discoverWorldDesc: 'Open the Biteo app and start your journey to discover interesting places and useful services right where you live.',
    downloadIOS: 'Download on iOS',
    downloadAndroid: 'Download on Android',

    // Grocery Page
    groceryHero: 'Grocery Shopping',
    groceryTitle: 'Smart Grocery, Save Time',
    groceryDesc: 'Buy groceries and essentials quickly and conveniently right where you live. Fresh food, delivered to your door, no need to go to the market.',
    orderNow: 'Order Now',
    scheduleDelivery: 'Schedule Delivery',
    products: 'Products',
    orders: 'Orders',
    areas: 'Areas',
    fastDelivery: 'Fast Delivery',
    howItWorks: 'How It Works',
    selectProducts: 'Select Products',
    selectProductsDesc: 'Browse and select the groceries you need from a diverse catalog',
    confirmOrder: 'Confirm Order',
    confirmOrderDesc: 'Check your cart and confirm with delivery information',
    receiveOrder: 'Receive Order',
    receiveOrderDesc: 'The shopper will deliver to your door at your chosen time',
    groceryFeatures: 'Key Features',
    easySelect: 'Easy Selection',
    easySelectDesc: 'Browse complete food catalog, view transparent prices and select favorite products.',
    fastDelivery2: 'Fast Delivery',
    fastDelivery2Desc: 'Receive in 2-4 hours or schedule delivery that fits your schedule.',
    freeDelivery: 'Free Delivery',
    freeDeliveryDesc: 'Free delivery for orders from 200,000đ. Delivery fee from just 15,000đ.',
    freshFood: 'Fresh Food',
    freshFoodDesc: '100% commitment to fresh products with clear origins from reputable suppliers.',
    easyReturn: 'Easy Returns',
    easyReturnDesc: 'Return policy within 24 hours if products do not meet requirements.',
    repeatBuy: 'Repeat Purchase',
    repeatBuyDesc: 'Save regular shopping lists, order with just one tap.',
    productCategories: 'Product Categories',
    popularProducts: 'Popular Products',
    startShopping: 'Start Shopping Today!',
    startShoppingDesc: 'Download the Biteo app and experience convenient grocery shopping. Free delivery on your first order!',

    // Shopping Page
    shoppingHero: 'Shopping',
    shoppingTitle: 'Vietnamese Specialties at Your Fingertips',
    shoppingDesc: 'Discover and shop local specialties, OCOP products and curated items from across Vietnam. Delivered to your door, easy payment.',
    shopNow: 'Shop Now',
    viewOffers: 'View Offers',
    shopProducts: 'Products',
    sellers: 'Sellers',
    shoppingFeatures: 'Key Features',
    localSpecialties: 'Local Specialties',
    localSpecialtiesDesc: 'Discover and shop specialties from all over Vietnam, from Trang Bang rice paper to Buon Ma Thuot coffee.',
    fastDelivery3: 'Fast Delivery',
    fastDelivery3Desc: 'Receive in 24-48h with logistics system covering all 63 provinces.',
    qualityProducts: 'Quality Products',
    qualityProductsDesc: 'All products are vetted, ensuring quality and clear origins.',
    securePayment: 'Secure Payment',
    securePaymentDesc: 'Multiple payment methods, absolute information security.',
    favorites: 'Favorites & Ratings',
    favoritesDesc: 'Save favorite products, view reviews from real buyers.',
    greatOffers: 'Great Offers',
    greatOffersDesc: 'Discount codes, regular promotions and loyalty point programs.',
    productCategories2: 'Product Categories',
    northSpecialties: 'Northern Specialties',
    centralSpecialties: 'Central Specialties',
    southSpecialties: 'Southern Specialties',
    featuredProducts: 'Featured Products',
    topSellers: 'Top Sellers',
    shopNow2: 'Shop Specialties Today!',
    shopNow2Desc: 'Download the Biteo app to discover a rich catalog of specialties from across Vietnam. Get 20% off your first order!',

    // Travel Page
    travelHero: 'Travel',
    travelTitle: 'Explore Vietnam Completely',
    travelDesc: 'Book rooms, find destinations and plan memorable journeys. All in one app with the best prices.',
    exploreNow: 'Explore Now',
    planTrip: 'Plan Trip',
    destinations: 'Destinations',
    hotels: 'Hotels',
    travelers: 'Travelers',
    travelFeatures: 'Key Features',
    smartSearch2: 'Smart Search',
    smartSearch2Desc: 'Explore destinations with filters by travel type, budget, location.',
    diverseDestinations: 'Diverse Locations',
    diverseDestinationsDesc: 'From beaches, mountains to modern cities - all in Biteo.',
    bookHotel: 'Book Hotel',
    bookHotelDesc: 'Compare prices, view reviews and book hotels at the best rates.',
    bookTicket: 'Book Travel Tickets',
    bookTicketDesc: 'Buy plane tickets, train tickets, tours directly on the app.',
    travelGuide: 'Travel Guide',
    travelGuideDesc: 'Explore travel experiences, check-in spots, local cuisine.',
    saveFavorites2: 'Save Favorites',
    saveFavorites2Desc: 'Save dream destinations to plan your next trip.',
    popularDestinations: 'Popular Destinations',
    travelTypes: 'Travel Types',
    beachTravel: 'Beach Travel',
    mountainTravel: 'Mountain Travel',
    culturalTravel: 'Cultural Travel',
    adventure: 'Adventure',
    familyTravel: 'Family Travel',
    foodTour: 'Food Tour',
    nextTrip: 'Ready for Your Next Trip?',
    nextTripDesc: 'Plan, book and explore amazing destinations with Biteo. Book today for special offers!',

    // Culinary Page
    culinaryHero: 'Culinary',
    culinaryTitle: 'Explore Flavors Across Vietnam',
    culinaryDesc: 'Find restaurants, eateries, cafes and distinctive flavors around you. Book tables online, view real reviews from the community.',
    findFoodNear: 'Find Food Near Me',
    specificSearch: 'Specific Search',
    restaurants: 'Restaurants & Eateries',
    culinaryFeatures: 'Key Features',
    smartSearch3: 'Smart Search',
    smartSearch3Desc: 'Find restaurants near you with diverse filters by dish type, distance, ratings.',
    accurateLocation: 'Accurate Location',
    accurateLocationDesc: 'View restaurant location on map, get directions quickly.',
    realRatings: 'Real Ratings',
    realRatingsDesc: 'Millions of reviews from real users, helping you choose the right place to eat.',
    bookOnline: 'Book Tables Online',
    bookOnlineDesc: 'Book a table at your favorite restaurant, no need to call and wait.',
    transparentInfo: 'Transparent Information',
    transparentInfoDesc: 'View prices, menus, opening hours clearly before deciding.',
    saveFavorites3: 'Save Favorites',
    saveFavorites3Desc: 'Create a list of favorite eateries, share with friends easily.',
    cuisines: 'Diverse Cuisines',
    restaurants2: 'Featured Restaurants',
    featured: 'Featured',
    hungryNow: 'Hungry? Find Food Now!',
    hungryNowDesc: 'Open the Biteo app, find eateries near you, book a table and enjoy delicious food.',

    // Video Page
    videoHero: 'Entertainment Video',
    videoTitle: 'Unlimited Entertainment, Anytime Anywhere',
    videoDesc: 'Discover a rich entertainment video library from Vietnamese creator community. Short videos, short films, local content - all in one app.',
    downloadApp: 'Download App',
    tryNow: 'Try Now',
    views: 'Views',
    videos: 'Videos',
    creators: 'Creators',
    users2: 'Users',
    videoFeatures: 'Key Features',
    diverseContent: 'Diverse Content',
    diverseContentDesc: 'From entertainment videos, short films to rich local content from across Vietnam.',
    creativeCommunity: 'Creative Community',
    creativeCommunityDesc: 'Connect with millions of Vietnamese creators, share and explore unique content.',
    smoothExperience: 'Smooth on All Devices',
    smoothExperienceDesc: 'Seamless video watching experience on phones, tablets and smart TVs.',
    personalizedContent: 'Personalized Content',
    personalizedContentDesc: 'AI algorithm learns your preferences, suggests suitable videos every day.',
    easyShare: 'Easy Sharing',
    easyShareDesc: 'Save, share favorite videos to social media with just one tap.',
    unlimitedFavorites: 'Unlimited Favorites',
    unlimitedFavoritesDesc: 'Create your own video collection, watch anytime you want.',
    popularCategories: 'Popular Categories',
    trendingCreators: 'Trending Creators',
    followers: 'followers',
    exploreVideo: 'Ready to Explore the Video World?',
    exploreVideoDesc: 'Download the Biteo app now and start your journey to discover a massive entertainment video library from the Vietnamese creator community.',

    // Discover categories
    catCafe: 'Cafes',
    catPark: 'Parks',
    catRestaurant: 'Restaurants',
    catSpa: 'Spa & Salon',
    catGym: 'Gyms',
    catShop: 'Shops',
    turtleLake: 'Famous check-in spot',
    benThanhMarket: 'Distinctive traditional market',
    nguyenHueStreet: 'Lively nightlife area',
    hcmcMuseum: 'Cultural and historical heritage',

    // Grocery categories
    catVegetables: 'Vegetables',
    catMeat: 'Fresh Meat',
    catSeafood: 'Seafood',
    catDairy: 'Eggs & Dairy',
    catSpices: 'Spices',
    catDry: 'Dry Goods',

    // Shopping categories
    catNorth: 'Northern Specialties',
    catCentral: 'Central Specialties',
    catSouth: 'Southern Specialties',
    catOCOP: 'OCOP',
    catAgri: 'Agriculture',
    catCraft: 'Handicrafts',
    shopBanhtrang: 'Trang Bang Rice Paper',
    shopCoffee: 'Cau Dat Arabica Coffee',
    shopBanhda: 'Hai Phong Crab Noodle',
    shopNuocmam: 'Phu Quoc Fish Sauce',
    shopVungdat: 'Specialty Land',
    shopOCOPStore: 'OCOP Store',
    shopNongsan: 'Vietnam Agriculture',
    shopBaMien: '3 Regions Specialties',

    // Travel destinations
    destDanang: 'Da Nang',
    destDanangType: 'Beach & Mountain',
    destPhuquoc: 'Phu Quoc',
    destPhuquocType: 'Island',
    destSapa: 'Sapa',
    destSapaType: 'Mountain',
    destHoian: 'Hoi An',
    destHoianType: 'Cultural',
    destNhatrang: 'Nha Trang',
    destNhatrangType: 'Beach',
    destHagiang: 'Ha Giang',
    destHagiangType: 'Mountain',

    // Culinary
    catVietnam: 'Vietnam',
    catJapan: 'Japan',
    catKorea: 'Korea',
    catItaly: 'Italy',
    catChina: 'China',
    catThailand: 'Thailand',
    restBepMe: 'Mother Manh Kitchen',
    restVietnam: 'Vietnam',
    restSushi: 'Sushi King',
    restJapan: 'Japan',
    restKBBQ: 'KBBQ House',
    restKorea: 'Korea',
    restPizza: 'Pizza Milano',
    restItaly: 'Italy',

    // Video categories
    catShortFilm: 'Short Films',
    catVideoFood: 'Food',
    catVideoTravel: 'Travel',
    catMusic: 'Music',
    catComedy: 'Comedy',
    catEducation: 'Education',
    creatorVietnam: 'Vietnam Travel',
    creatorFood: 'Food Paradise',
    creatorComedy: 'Comedy VN',
    creatorTravelKid: 'Travel Kid',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('vi')

  useEffect(() => {
    const saved = localStorage.getItem('biteo-language') as Language | null
    if (saved && (saved === 'vi' || saved === 'en')) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('biteo-language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
